config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "items#index"
  resources :items, except: [:index] do
    resources :item_purchases, only: [:index, :create]
    collection do
      get 'search'
      get 'detailed_search'
    end
  end
  get 'tags/search', to: 'tags#search'
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :category
  belongs_to_active_hash :status
  belongs_to_active_hash :shipping_fee
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :shipping_time
  has_one_attached :image
  belongs_to :user
  has_one :item_purchase
  has_many :item_tag_relations
  has_many :tags, through: :item_tag_relations, dependent: :destroy

  validates :sold_out, inclusion: { in: [true, false] }
  validates :image, presence: true
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :search_item, only: [:index, :show, :search]

  def index
    @items = Item.with_attached_image.order('created_at DESC')
  end

  def new
    @item = Item.new
    @item_tag = ItemTag.new
  end

  def create
    @item_tag = ItemTag.new(item_params)
    if @item_tag.valid?
      @item_tag.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    set_tag_list
  end

  def edit
    @item_tag = ItemTag.new
    redirect_to item_path(@item) if current_user.id != @item.user_id
  end

  def update
    @item_tag = ItemTag.new(item_params.merge(item_id: params[:id]))
    if @item_tag.valid?(:update)
      @item_tag.update
      redirect_to item_path(params[:id])
    else
      render :edit
    end
  end

  def destroy
    if current_user.id != @item.user_id
      redirect_to root_path
    else
      if @item.destroy
        redirect_to root_path
      else
        render :show
      end
    end
  end

  def search
    redirect_to root_path if params[:q].nil?
    @results = @p.result.with_attached_image
  end

  def detailed_search
    redirect_to root_path if params[:q].nil?
    search_item_form = SearchItemForm.new(search_params)
    @p, @results = search_item_form.search
    @results = search_item_form.sort_results
    render :search
  end

  private

  def item_params
    params.require(:item).permit(:name, :text, :category_id, :status_id, :shipping_fee_id, :prefecture_id, :shipping_time_id, :price, :image, tags: { name: [] }).merge(user_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  rescue StandardError
    redirect_to root_path
  end

  def set_tag_list
    @tag_list = []
    @item.tags.each do |tag|
      @tag_list << tag.name
    end
  end

  def search_item
    @p = Item.ransack(params[:q])  # 検索オブジェクトを生成
  end

  def search_params
    params.require(:q).permit(:name_i_cont_any, :tags_name_i_cont_any, :price_gteq, :price_lteq, item_sort: [:id], category: [:id], status: { ids: [] }, shipping_fee: { ids: [] }, sales_status: { ids: [] })
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_item.html.erb
<li class='list'>
  <%= link_to item_path(item) do %>
    <div class='item-img-content'>
      <%= image_tag item.image, class: "item-img" %>
      <% if item.sold_out %>
        <div class='sold-out'>
          <span>Sold Out!!</span>
        </div>
      <% end %>
    </div>

    <div class='item-info'>
      <h3 class='item-name'>
        <%= item.name %>
      </h3>
      <div class='item-price'>
        <span><%= item.price %>円<br>(税込み)</span>
        <div class='star-btn'>
          <%= image_tag "star.png", class:"star-icon" %>
          <span class='star-count'>0</span>
        </div>
      </div>
    </div>
  <% end %>
</li>

app/views/items/_item_form.html.erb
<div class="items-sell-contents">

  <header class="items-sell-header">
    <%= link_to image_tag('furima-logo-color.png' , size: '185x50'), "/" %>
  </header>

  <div class="items-sell-main">
    <h2 class="items-sell-title">商品の情報を入力</h2>

    <%= form_with model: item, url: path, method: http_method, local: true do |f| %>
      
      <%= render 'shared/error_messages', model: item_tag %>

      <%# 出品画像 %>
      <div class="img-upload">
        <div class="weight-bold-text">
          出品画像
          <span class="indispensable">必須</span>
        </div>
        <div class="click-upload">
          <p>
            クリックしてファイルをアップロード
          </p>
          <%= f.file_field :image, id:"item-image" %>
        </div>
      </div>
      <%# /出品画像 %>

      <%# 商品名と商品説明 %>
      <div class="new-items">
        <div class="weight-bold-text">
          商品名
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :name, class:"items-text", id:"item-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
        <div class="items-explain">
          <div class="weight-bold-text">
            商品の説明
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_area :text, class:"items-text", id:"item-info", placeholder:"商品の説明（必須 1,000文字まで）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。" ,rows:"7" ,maxlength:"1000" %>
        </div>
      </div>
      <%# /商品名と商品説明 %>

      <%# 商品の詳細 %>
      <div class="items-detail">
        <div class="weight-bold-text">商品の詳細</div>
        <div class="form">
          <div class="weight-bold-text">
            カテゴリー
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
          <div class="weight-bold-text">
            タグ (3つまで)
            <span class="form-any">任意</span>
          </div>
          <% if request.path_info.match(/items\/\d+/) && item.tags != [] %>
            <% count = 1 %>
            <% item.tags.each do |tag| %>
              <%= f.fields_for tag do |t| %>
                <%= t.text_field :name, class: "tags-text", id:"tag-name-#{count}", placeholder: "タグ（任意 10文字まで)", maxlength: "10", name: "item[tags][name][]", multiple: true %>
              <% end %>
              <% count += 1 %>
            <% end %>
              <div class="search-result" id="search-result"></div>
              <div class="tag-button">
                <button type="button" id="add-tag-button">+</button>
                <button type="button" id="remove-tag-button">-</button>
              </div>
          <% else %>
            <%= f.fields_for :tag do |t| %>
              <%= t.text_field :name, class: "tags-text", id:"tag-name-1", placeholder: "タグ（任意 10文字まで)", maxlength: "10", name: "item[tags][name][]", multiple: true %>
              <div class="search-result" id="search-result"></div>
              <div class="tag-button">
                <button type="button" id="add-tag-button">+</button>
                <button type="button" id="remove-tag-button">-</button>
              </div>
            <% end %>
          <% end %>
          <div class="weight-bold-text">
            商品の状態
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:status_id, Status.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
        </div>
      </div>
      <%# /商品の詳細 %>

      <%# 配送について %>
      <div class="items-detail">
        <div class="weight-bold-text question-text">
          <span>配送について</span>
          <a class="question" href="#">?</a>
        </div>
        <div class="form">
          <div class="weight-bold-text">
            配送料の負担
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:shipping_fee_id, ShippingFee.all, :id, :name, {}, {class:"select-box", id:"item-shipping-fee-status"}) %>
          <div class="weight-bold-text">
            発送元の地域
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box", id:"item-prefecture"}) %>
          <div class="weight-bold-text">
            発送までの日数
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:shipping_time_id, ShippingTime.all, :id, :name, {}, {class:"select-box", id:"item-scheduled-delivery"}) %>
        </div>
      </div>
      <%# /配送について %>

      <%# 販売価格 %>
      <div class="sell-price">
        <div class="weight-bold-text question-text">
          <span>販売価格<br>(¥300〜9,999,999)</span>
          <a class="question" href="#">?</a>
        </div>
        <div>
          <div class="price-content">
            <div class="price-text">
              <span>価格</span>
              <span class="indispensable">必須</span>
            </div>
            <span class="sell-yen">¥</span>
            <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"例）300" %>
          </div>
          <div class="price-content">
            <span>販売手数料 (10%)</span>
            <span>
              <span id='add-tax-price'></span>円
            </span>
          </div>
          <div class="price-content">
            <span>販売利益</span>
            <span>
              <span id='profit'></span>円
            </span>
          </div>
        </div>
      </div>
      <%# /販売価格 %>

      <%# 注意書き %>
      <div class="caution">
        <p class="sentence">
          <a href="#">禁止されている出品、</a>
          <a href="#">行為</a>
          を必ずご確認ください。
        </p>
        <p class="sentence">
          またブランド品でシリアルナンバー等がある場合はご記載ください。
          <a href="#">偽ブランドの販売</a>
          は犯罪であり処罰される可能性があります。
        </p>
        <p class="sentence">
          また、出品をもちまして
          <a href="#">加盟店規約</a>
          に同意したことになります。
        </p>
      </div>
      <%# /注意書き %>

      <% if request.path_info.match(/items\/\d+/) %>
        <%# 下部ボタン 編集時%>
        <div class="sell-btn-contents">
          <%= f.submit "変更する" ,class:"sell-btn" %>
          <%=link_to 'もどる', "#", class:"back-btn" %>
        </div>
        <%# /下部ボタン 編集時%>
      <% else %>
        <%# 下部ボタン 出品時%>
        <div class="sell-btn-contents">
          <%= f.submit "出品する" ,class:"sell-btn" %>
          <%=link_to 'もどる', root_path, class:"back-btn" %>
        </div>
        <%# /下部ボタン 出品時%>
      <% end %>

    <% end %>
  </div>

  <footer class="items-sell-footer">
    <ul class="menu">
      <li><a href="#">プライバシーポリシー</a></li>
      <li><a href="#">フリマ利用規約</a></li>
      <li><a href="#">特定商取引に関する表記</a></li>
    </ul>
    <%= link_to image_tag('furima-logo-color.png' , size: '185x50'), "/" %>
    <p class="inc">
      ©︎Furima,Inc.
    </p>
  </footer>
</div>

app/views/items/edit.html.erb
<%= render partial: 'item_form', locals: { item: @item, item_tag: @item_tag, path: item_path(@item), http_method: "PATCH"} %>

app/views/items/index.html.erb
<%= render "shared/header" %>
<div class='main'>

  <%# 画面上部の「人生を変えるフリマアプリ」帯部分 %>
  <div class='title-contents'>
    <h2 class='service-title'>
      人生を変えるフリマアプリ
    </h2>
    <p class='service-explain'>
      FURIMAはだれでもかんたんに出品・購入できる
    </p>
    <p class='service-explain'>
      フリマアプリです
    </p>
    <div class='store-btn'>
      <%= link_to image_tag("https://linkmaker.itunes.apple.com/ja-jp/badge-lrg.svg?releaseDate=2011-09-21&kind=iossoftware&bubble=ios_apps", class:"apple-btn"), "#" %>
      <%= link_to image_tag("dl-android.png", class:"google-btn"), "#" %>
    </div>
  </div>
  <%# //画面上部の「人生を変えるフリマアプリ」帯部分  %>

  <%# FURIMAが選ばれる3つの理由部分 %>
  <div class='select-reason-contents'>
    <h2 class='title'>
      FURIMAが選ばれる3つの理由
    </h2>
    <ul class='reason-lists'>
      <li class='list'>
        <%= image_tag "furima-intro01.png", class:"list-pict" %>
        <span class='reason-list-number'>1</span>
        <h3 class='reason-list-text'>
          <span class='reason-list-blue-text'>3分</span>
          ですぐに出品
        </h3>
        <p class='reason-list-description'>
          スマホで入力するだけで簡単に出品できる！
        </p>
      </li>
      <li class='list'>
        <%= image_tag "furima-intro02.png", class:"list-pict" %>
        <span class='reason-list-number'>2</span>
        <h3 class='reason-list-text'>
          <span class='reason-list-blue-text'>シンプル</span>
          で使いやすい
        </h3>
        <p class='reason-list-description'>
          めんどくさい入力は必要なく、検索も購入もスムーズ！
        </p>
      </li>
      <li class='list'>
        <%= image_tag "furima-intro03.png", class:"list-pict" %>
        <span class='reason-list-number'>3</span>
        <h3 class='reason-list-text'>
          手数料
          <span class='reason-list-blue-text'>業界最安</span>
        </h3>
        <p class='reason-list-description'>
          最大3%でお得に出品&購入！
        </p>
      </li>
    </ul>
  </div>
  <%# //FURIMAが選ばれる3つの理由部分 %>

  <%# 画面中央の「会員数日本一位」帯部分 %>
  <div class='ad-contents'>
    <h2 class='ad-title'>
      会員数日本一位
    </h2>
    <p class='ad-explain'>
      FURIMAは、フリマアプリで最も人気。
    </p>
    <p class='ad-explain'>
      出品・購入回数も業界最多です！
    </p>
    <p class='ad-explain'>
      ほしかったあの商品に出会えるかもしれません。
    </p>
    <div class='store-btn'>
      <%= link_to image_tag("https://linkmaker.itunes.apple.com/ja-jp/badge-lrg.svg?releaseDate=2011-09-21&kind=iossoftware&bubble=ios_apps", class:"apple-btn"), "#" %>
      <%= link_to image_tag("dl-android.png", class:"google-btn"), "#" %>
    </div>
  </div>
  <%# //画面中央の「会員数日本一位」帯部分 %>

  <%# FURIMAの特徴 %>
  <div class='feature-contents'>
    <h2 class='title'>
      FURIMAの特徴
    </h2>
    <ul class='feature-lists'>
      <li class='list'>
        <%= image_tag "furima-intro04.png", class:"list-pict" %>
        <h3 class='feature-list-text'>
          簡単に売り買いできる
        </h3>
        <p class='feature-list-description'>
          スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
        </p>
      </li>
      <li class='list'>
        <%= image_tag "furima-intro05.png", class:"list-pict" %>
        <h3 class='feature-list-text'>
          売上金は即日振込みに対応
        </h3>
        <p class='feature-list-description'>
          午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします。
        </p>
      </li>
      <li class='list'>
        <%= image_tag "furima-intro06.png", class:"list-pict" %>
        <h3 class='feature-list-text'>
          様々な支払いに対応
        </h3>
        <p class='feature-list-description'>
          お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。
        </p>
      </li>
    </ul>
  </div>
  <%# //FURIMAの特徴 %>

  <%# 商品一覧 %>
  <div class='item-contents'>
    <h2 class='title'>ピックアップカテゴリー</h2>
    <%= link_to '新規投稿商品', "#", class: "subtitle" %>
    <ul class='item-lists'>
      <%= render partial: 'item', collection: @items %>
    </ul>
  </div>
  <%# //商品一覧 %>
</div>
<div class='purchase-btn'>
  <span class='purchase-btn-text'>出品する</span>
  <a href= '/items/new'>
    <%= image_tag 'camera.png' , size: '185x50' ,class: "purchase-btn-icon" %>
  </a>
</div>
<%= render "shared/footer" %>

app/views/items/new.html.erb
<%= render partial: 'item_form', locals: { item: @item, item_tag: @item_tag, path: items_path, http_method: "POST"} %>

app/views/items/search.html.erb
<%= render "shared/header" %>

<div class = 'search-content'>
  <div class = 'search-side'>
    <%= search_form_for @p, class: "detailed-search-form", id: "detailed-item-search", url: detailed_search_items_path do |f| %>
      <div class='search-form-group'>
        <%= f.fields_for :item_sort do |i| %>
          <%= i.collection_select :id, ItemSort.all, :id, :name, {}, {class:"search-sort", id:"search-item-sort"} %>
        <% end %>
      </div>
      <div class='search-dropdown-content'>
        <h3 class='detailed-search-text'>詳細検索</h3>
        <div class='search-form-group'>
            <span>キーワードを追加する</span>
            <%= f.search_field :name_i_cont_any, class: 'search-input', placeholder: 'キーワード' %>
        </div>
        <div class='search-form-group'>
          <label>
            <span>カテゴリーを選択する</span>
          </label>
          <%= f.fields_for :category do |i| %>
            <%= i.collection_select :id, SearchCategory.all, :id, :name, {}, {class:"search-select"} %>
          <% end %>
        </div>
        <div class='search-form-group'>
          <label>
            <span>タグ名から探す</span>
          </label>
          <%= f.search_field :tags_name_i_cont_any, class:"search-input" , id:"tag-name-1", placeholder: 'タグ'%>
          <div class="search-result" id="search-result"></div>
        </div>
        <div class='search-form-group'>
          <label>
            <span>価格を選択する</span>
          </label>
          <%= f.fields_for :price do |i| %>
            <%= i.collection_select :id, SearchPrice.all, :id, :name, {}, {class:"search-select", id:'search-price-select'} %>
          <% end %>
            <%= f.search_field :price_gteq, class: 'search-price', id:'search-price-min', placeholder: '円' %>
            <span>~<span>
            <%= f.search_field :price_lteq, class: 'search-price', id: 'search-price-max', placeholder: '円' %>
        </div>
        <div class='search-form-group'>
          <label>
            <span>商品の状態</span>
          </label>
          <div class='search-checkboxes'>
            <% SearchStatus.all.each do |s| %>
              <div class='search-checkbox'>
                <input type="checkbox" value=<%="#{s.id}"%> name="q[status][ids][]" id=<%="q_status_ids_#{s.id}"%> class="q_status_ids">
                <label for=<%="q_status_ids_#{s.id}"%>><%="#{s.name}"%></label>
              </div>
            <% end %>
          </div>
        </div>
        <div class='search-form-group'>
          <label>
            <span>配送料の負担</span>
          </label>
          <div class='search-checkboxes'>
            <% SearchShippingFee.all.each do |s| %>
              <div class='search-checkbox'>
                <input type="checkbox" value=<%="#{s.id}"%> name="q[shipping_fee]][ids][]" id=<%="q_shipping_fee_ids_#{s.id}"%> class="q_shipping_fee_ids">
                <label for=<%="q_shipping_fee_ids_#{s.id}"%>><%="#{s.name}"%></label>
              </div>
            <% end %>
          </div>
        </div>
        <div class='search-form-group'>
          <label>
            <span>販売状況</span>
          </label>
          <div class='search-checkboxes'>
            <% SalesStatus.all.each do |s| %>
              <div class='search-checkbox'>
                <input type="checkbox" value=<%="#{s.id}"%> name="q[sales_status]][ids][]" id=<%="q_sales_status_ids_#{s.id}"%> class="q_sales_status_ids">
                <label for=<%="q_sales_status_ids_#{s.id}"%>><%="#{s.name}"%></label>
              </div>
            <% end %>
          </div>
        </div>
        <div class='search-button-form'>
          <button type='button' class='detailed-search-button clear-button' id='clear-button'>クリア</button>
          <button type='submit' class='detailed-search-button submit-button'>検索</button>
        </div>
      </div>
    <% end %>
  </div>

  <div class='search-main'>
    <div class='item-search-result'>
      <% if @results.length !=0 %>
        <div class='item-contents'>
          <h2 class='search-title-head'><%= params[:q][:name_i_cont_any] %>
            <span class='search-title-text' >の検索結果</span>
          </h2>
          <ul class='item-lists'>
            <%= render partial: 'item', collection: @results %>
          </ul>
        </div>
      <% else %>
        <div class='item-contents'>
          該当する商品はありません
        </div>
      <% end %>
    </div>
  </div>

  <div class='purchase-btn'>
    <span class='purchase-btn-text'>出品する</span>
    <a href= '/items/new'>
      <%= image_tag 'camera.png' , size: '185x50' ,class: "purchase-btn-icon" %>
    </a>
  </div>
</div>

<%= render "shared/footer" %>

app/views/items/show.html.erb
<%= render "shared/header" %>

<%# 商品の概要 %>
<div class="item-show">
  <div class="item-box">
    <h2 class="name">
      <%= @item.name %>
    </h2>
    <div class='item-img-content'>
      <%= image_tag @item.image ,class:"item-box-img" %>
      <% if @item.sold_out %>
        <div class='sold-out'>
          <span>Sold Out!!</span>
        </div>
      <% end %>
    </div>
    <div class="item-price-box">
      <span class="item-price">
        <%= @item.price %>
      </span>
      <span class="item-postage">
        <% if @item.shipping_fee.id == 2 %>
          (税込) 着払い
        <% else %>
          (税込) 送料込み
        <% end %>
      </span>
    </div>

    <% if current_user && (current_user.id == @item.user.id) %>
      <%= link_to '商品の編集', edit_item_path(@item), method: :get, class: "item-red-btn" %>
      <p class='or-text'>or</p>
      <%= link_to '削除', item_path(@item), method: :delete, class:'item-destroy' %>
    <% else %>
      <% unless @item.sold_out %>
        <%= link_to '購入画面に進む', item_item_purchases_path(@item), class:"item-red-btn"%>
      <% end %>
    <% end %>

    <div class="item-explain-box">
      <span><%= @item.text %></span>
    </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">出品者</th>
          <td class="detail-value"><%= @item.user.nickname %></td>
        </tr>
        <tr>
          <th class="detail-item">カテゴリー</th>
          <td class="detail-value"><%= @item.category.name %></td>
        </tr>
        <% if @item.tags != [] %>
          <tr>
            <th class="detail-item">タグ</th>
            <td class="detail-value"><%= @tag_list.join(',') %></td>
          </tr>
        <% end %>
        <tr>
          <th class="detail-item">商品の状態</th>
          <td class="detail-value"><%= @item.status.name %></td>
        </tr>
        <tr>
          <th class="detail-item">配送料の負担</th>
          <td class="detail-value"><%= @item.shipping_fee.name %></td>
        </tr>
        <tr>
          <th class="detail-item">発送元の地域</th>
          <td class="detail-value"><%= @item.prefecture.name %></td>
        </tr>
        <tr>
          <th class="detail-item">発送日の目安</th>
          <td class="detail-value"><%= @item.shipping_time.name %></td>
        </tr>
      </tbody>
    </table>
    <div class="option">
      <div class="favorite-btn">
        <%= image_tag "star.png" ,class:"favorite-star-icon" ,width:"20",height:"20"%>
        <span>お気に入り 0</span>
      </div>
      <div class="report-btn">
        <%= image_tag "flag.png" ,class:"report-flag-icon" ,width:"20",height:"20"%>
        <span>不適切な商品の通報</span>
      </div>
    </div>
  </div>
  <%# /商品の概要 %>

  <div class="comment-box">
    <form>
      <textarea class="comment-text"></textarea>
      <p class="comment-warn">
        相手のことを考え丁寧なコメントを心がけましょう。
        <br>
        不快な言葉遣いなどは利用制限や退会処分となることがあります。
      </p>
      <button type="submit" class="comment-btn">
        <%= image_tag "comment.png" ,class:"comment-flag-icon" ,width:"20",height:"25"%>
        <span>コメントする<span>
      </button>
    </form>
  </div>
  <div class="links">
    <a href="#" class="change-item-btn">
      ＜ 前の商品
    </a>
    <a href="#" class="change-item-btn">
      後ろの商品 ＞
    </a>
  </div>
  <a href="#" class='another-item'><%= "商品のカテゴリー名" %>をもっと見る</a>
</div>

<%= render "shared/footer" %>